### ISSUE TITLE
problem z nmp install

### ISSUE THREAD

**Issue by kalanel** [daftcode/frontend_levelup_2018#33]
siemka
próbowałem zrobić commend bota do cs go. Wszytko szło dobrze, normlnie dopóki nie musiałem wpisać npm install. Po wpisaniu tego do WinowsPowerShell pojawiał sie błąd (zdjęcie). To samo dzieje się po wpisaniu npm install sqlite3. Chyba próbowałem wszystkiego.

Pobierałem na nowo 3 razy node (instalowałem i na dysku C i na dysku D

pobierałem ten plik (potrzebny do zrobienia commend bota) 3 razy (instalowalem i na C i na D)
https://github.com/daftcode/frontend_levelup_2018/files/4518331/csgo-commend-bot-master2.zip

standardowo kilka razy reset kompa

pobrałem najnowszego pythona (na początku na dysk C potem jak nie działało na dysk D)

co mogę zrobić żeby to zadziałało i żeby zrobić tego commend bota?

![Bez_tytuu1](https://user-images.githubusercontent.com/42584496/80020798-e308dd00-84d9-11ea-9f49-ec8a06d087f6.png)
![Bez_tytuu2](https://user-images.githubusercontent.com/42584496/80020801-e3a17380-84d9-11ea-84d4-012bad5804f4.png)

tutaj błąd:

> sqlite3@4.1.0 install D:\csgo-commend-bot-master\csgo-commend-bot-master\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/node-v83-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.1.0 and node@14.0.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (D:\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (D:\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (D:\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:322:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:468:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "D:\\node.exe" "D:\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\csgo-commend-bot-master\\csgo-commend-bot-master\\node_modules\\sqlite3\\lib\\binding\\node-v83-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=D:\\csgo-commend-bot-master\\csgo-commend-bot-master\\node_modules\\sqlite3\\lib\\binding\\node-v83-win32-x64" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd D:\csgo-commend-bot-master\csgo-commend-bot-master\node_modules\sqlite3
gyp ERR! node -v v14.0.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'D:\node.exe D:\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\csgo-commend-bot-master\csgo-commend-bot-master\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\csgo-commend-bot-master\csgo-commend-bot-master\node_modules\sqlite3\lib\binding\node-v83-win32-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\csgo-commend-bot-master\csgo-commend-bot-master\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "D:\\node.exe" "D:\\csgo-commend-bot-master\\csgo-commend-bot-master\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\csgo-commend-bot-master\csgo-commend-bot-master\node_modules\sqlite3
node-pre-gyp ERR! node -v v14.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'D:\node.exe D:\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\csgo-commend-bot-master\csgo-commend-bot-master\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\csgo-commend-bot-master\csgo-commend-bot-master\node_modules\sqlite3\lib\binding\node-v83-win32-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.1.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mateu\AppData\Roaming\npm-cache\_logs\2020-04-22T15_54_07_830Z-debug.log
PS D:\csgo-commend-bot-master\csgo-commend-bot-master>

**Comment by kalanel** [comment]
przydałaby się jak najszybsza odpowiedź. Z góry dzięki

**Comment by mpsujek** [comment]
Cześć,

mam wrażenie że masz kilka błędów tak na pierwszy rzut oka oceniam.

Po pierwsze download(403) czyli wygląda na to próbujesz pobrać zipa do którego nie masz uprawnień.

Kolejne errory wyglądają jakbyś nie miał zainstalowanego Pythona
https://hisk.io/how-to-fix-node-js-gyp-err-cant-find-python-executable-python-on-windows/ 

Ogółem powodzenia :) Mam nadzieję że ktoś jeszcze się wypowie
